### ISSUE TITLE
ec:tag range Literal

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [ebu/ebucoreplus#346]
I wanna to discuss about that usage of Literal of type, that does not allow a definition of an IRI.

It may relevant to have a range that allow Literal or IRI for a tag to may have description, etc. around a tag.

@alexander-schulze @JuergenGrupp @tormodv do you have any suggestion to define that in OWL2 ?

**Comment by alexander-schulze** [comment]
The OWL 2 construct in the above case would look like follows:

ec:EditorialObject rdf:type owl:Class ;
                   rdfs:subClassOf ec:Asset ,
                                   :
                                   [ rdf:type owl:Restriction ;
                                     owl:onProperty ec:tag ;
                                     owl:allValuesFrom [ rdf:type rdfs:Datatype ;
                                                         owl:unionOf ( rdfs:Literal
                                                                       xsd:anyURI
                                                                     )
                                                       ]
                                   ] ,

**Comment by JuergenGrupp** [comment]
From today's meeting of the Editorial Committee: 
- We would not change the `tag` property to allow both data types, but rather recommend to use `topic` or `subject` as they both have the data type skos:concept, which is perfect for controlled vocabularies (classification schemes). 
- The property `tag` was intended to be used with words that appear in unmoderated environments, typically not using classification schemes.
As a result, the issue is not supported by the Editorial Committee and closed.
