### ISSUE TITLE
hasIdentifier

### ISSUE THREAD

**Issue by tormodv** [ebu/ebucoreplus#50]
The has identifier property have som subproperties: 
- :hasEidrIdentifier
- :hasIMediaIdentifier
- :hasIsanIdentifier

Why just those three, and furthermore as they point to a class, the Identifierclass have a type attribute that can point to any skos:Consept.

I think it is better use the superproperty hasIdentifier, and let the instance of the identifierclass explain its kind.

**Comment by alexandre-rouxel** [comment]
Agree, use hasIdentifier, it will faciliate the management of other identifiers.

**Comment by kimviljanen** [comment]
An Identifier class is more flexible both to specify the type but also some identifiers can probably be a combination of multiple fields and not one string.

**Comment by alexander-schulze** [comment]
I can understand that we use a top-level “Identifier” class (opposed to a simple literal), since this makes us very flexible regarding the representation of how an identifier is (or can be) composed, and of what (data) type it is etc. As far as I understand, here we provide a generic option that says, “you can store proprietary data” in the semantic EBU model.  However, the “Identifier” class does not have any descendants that describe a schema for any particular system or standard other than a “creation date/time“ field (which I’m wondering what this is supposed to manage here).

To me “hasIdentifier“ w/o sub properties is perfectly fine. However, we should provide the respective classes for those systems or standards that we intend to support, as a schema, like we do for the other entities as well. Otherwise, we would not have any semantics but an arbitrary open record for identifiers.

**Comment by tormodv** [comment]
The Identifier class might need to be better described perhaps.
